### ISSUE TITLE
Add better defaults and documentation

### ISSUE THREAD

**Issue by mstanciu552** [ahmedkhalf/jupyter-nvim#4]
So I've been trying to get started with using this plugin...but I have no idea what keymappings are available or how to run a cell or anything...
Can you  help?

**Comment by mstanciu552** [comment]
Thank you

**Comment by amtoine** [comment]
@Hooregi are you planning to add such support?
Would be pretty usefull to run and edit cells just as in `jupyter`

**Comment by rkabrick** [comment]
> @Hooregi are you planning to add such support?
> 
> Would be pretty usefull to run and edit cells just as in `jupyter`

Check out magma-nvim

**Comment by Hooregi** [comment]
> @Hooregi are you planning to add such support? Would be pretty useful to run and edit cells just as in `jupyter`

I'm not a maintainer, just a guy that read the docs haha.

**Comment by amtoine** [comment]
> 
> 
> 
> > @Hooregi are you planning to add such support? Would be pretty useful to run and edit cells just as in `jupyter`
> 
> I'm not a maintainer, just a guy that read the docs haha.

my bad! :o

**Comment by amtoine** [comment]
> > @Hooregi are you planning to add such support?
> > 
> > Would be pretty usefull to run and edit cells just as in `jupyter`
> 
> Check out magma-nvim

yep, just discovered this a few hours later!
thanks, i'll investigate that plugin.
